---
title: "Annual Plant Community and Monitoring Report - `r params$park`: `r format(Sys.Date(), '%Y-%m-%d')`"
output: html_document

params:
  park: "DefaultPark"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
```

```{r testingdataset}
park <- c("AGFO", "AGFO", "BADL", "DETO", "BADL", "DETO")
cover <- c("12", "11", "16", "13", "12", "17")
species <- c("brja", "brja", "brja", "brdi", "brdi","brdi")

park_data <- data.frame(park = park,
                        cover = cover,
                        species = species)
```

```{r filtering park}
park_filter <- park_data |> 
  filter(park == params$park)
```


#### Map of `r params$park` {.tabset}

```{r pressure, echo=FALSE}
ggplot() +
  geom_col(data = park_filter,
           aes(x = species,
               y = cover))
```

#### Table of Plot visits {.tabset}

```{r}

```

#### Table of Exotic Species {.tabset}

```{r}

```

#### Table of Species {.tabset}

```{r}

```

#### Table of Plot visits {.tabset}

```{r}

```
